### PR TITLE
Mobile mode

### PR DESCRIPTION
**Pull request by trinhdnk95**
- replace all media file by new media
- fixed some feedback from Erik
- update some view

### CODE REVIEW

**Comment by rocco-haro** [comment]
> demo.mp4

the header image looks compressed!

**Comment by trinhdnk95** [comment]
- fixed some style and image work not good when deploy
- fixed header image scale
- test speed load for landingPag
[ScreenRecorder_2022-10-27_1725ace5-dcbc-4a66-8510-5e588dedc253.webm](https://user-images.githubusercontent.com/81945451/198293087-35fd1788-3963-49d5-874b-043d0a96fd80.webm)
e

**Comment by trinhdnk95** [comment]
fixed all feedback from Erik
[a2b40d59-3959-4546-a7cf-1eef12b39fb7.webm](https://user-images.githubusercontent.com/81945451/200319540-5d2630b4-54e7-4659-b4dd-b8d9caf55026.webm)

**Comment by trinhdnk95** [comment]
- handle misssing click
- fixed some impact logic open form
[c5680835-8d3b-4bf4-b82b-2759a44e282e.webm](https://user-images.githubusercontent.com/81945451/201522672-e39039c8-2e2c-4fad-919e-663373ceca2e.webm)


-

**Pull request merged**
